version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing Terraform..."
      - curl -o /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      - unzip /tmp/terraform.zip -d /usr/local/bin/
      - echo "Installing pip..."
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - sudo python3 get-pip.py
      - echo "Installing Ansible..."
      - pip install ansible boto3  # Added `boto3` for AWS-related tasks
      - echo "Installing jq for JSON parsing..."
      - yum install -y jq
  pre_build:
    commands:
      - echo "Preparing Terraform configurations..."
      - ls -R
      - chmod +x ./scripts/terraform-build/terraform-eks.sh
  build:
    commands:
      - echo "Running Terraform script..."
      - ./scripts/terraform-build/terraform-eks.sh
      - echo "Extracting EKS cluster details..."
      - terraform -chdir=scripts/terraform-build output -json > eks-cluster-output.json

  post_build:
    commands:
      - echo "Terraform execution complete. Build finished."
      - echo "Running Ansible playbook to deploy the app..."
      - ls -R scripts/ 
      - cd ..
      - ansible-playbook -i localhost, ansible-playbook.yml --extra-vars "eks_cluster_name=$(jq -r '.cluster_name.value' eks-cluster-output.json)"
artifacts:
  files:
    - "**/*"
